/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operations.h"

#include <stdio.h>
#include <errno.h>

extern int err;

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
    
    host = argv[1];
    CLIENT *clnt;
    char *result_6;
    struct name auth_1_arg;
    char first1[100], second1[100];
    scanf("%s %s", first1, second1);//entering the directory and new directory path
	auth_1_arg.old = first1;
	auth_1_arg.final = second1;
	//printf("%s\n",auth_1_arg.old);
	clnt = clnt_create (host, OPERATIONS, OPERATIONS_VERS, "tcp");
	if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
			}

	result_6 = auth_1(&auth_1_arg, clnt);
	//printf("%s\n",result_6);
	if (result_6 == (char *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		//printf("%s is the return value\n",result_6 );
	if(*(result_6)=='n')
	{
	printf("permission denied\n");
	}

	else if(result_6!="n"){

	int choice;
	while(1){

		printf("What do u want to do\n1.Rename 2.Delete 3.Move 4.Change Mode 5.List Directory Contents\n");
		scanf("%d", &choice);
		if(choice==1){//user deccides to rename the directory
			CLIENT *clnt; //declaring client
			char  *result_1;
			struct name rename_1_arg;
			printf("Enter the path separated by a space for rename\n");
			char first[100], second[100];
			scanf("%s %s", first, second);//entering the directory and new directory path
			rename_1_arg.old = first;
			rename_1_arg.final = second;  
		//	rename_1_arg.old  = "/check";
		//	rename_1_arg.final = "/Check123";
		//	printf("%s\n",rename_1_arg.old );
			clnt = clnt_create (host, OPERATIONS, OPERATIONS_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

			result_1 = rename_1(&rename_1_arg, clnt);
			if (result_1 == (char *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			printf("\nRename operation has been performed\n---------------------------\n");

			clnt_destroy (clnt);

		}

		else if(choice==2){//user deccides to rename the directory
			CLIENT *clnt; //declaring client
			char  *result_2;
			char *path;
			char location[100];
			printf("Enter the path of the Directory you want to delete\n");
			scanf("%s", location);//entering the directory and new directory path
		//	fgets(path, 50, stdin);
		//	path = "/home/sahil/Desktop/check";
			path = location;
			printf("Path entered by you is %s\n", path);
			clnt = clnt_create (host, OPERATIONS, OPERATIONS_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

			result_2 = delete_1(&path, clnt);
			if (result_2 == (char *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			printf("\nDelete operation has been performed\n---------------------------\n");

			clnt_destroy (clnt);
		}
		

		else if(choice==3){//user deccides to Move the directory
			CLIENT *clnt; //declaring client
			char  *result_3;
			name  move_1_arg;
			printf("Enter the path separated by a space for a move\n");
			char first[100], second[100];
			scanf("%s %s", first, second);//entering the directory and new directory path
			move_1_arg.old = first;
			move_1_arg.final = second;  

			clnt = clnt_create (host, OPERATIONS, OPERATIONS_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

			result_3 = move_1(&move_1_arg, clnt);
			if (result_3 == (char *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			printf("\nMove operation has been performed\n---------------------------\n");

			clnt_destroy (clnt);

		}

		else if(choice ==4){
			CLIENT *clnt; //declaring client
			char  *result_4;
			char *path;
			char location1[5];
			char location2[100];
			printf("Enter the permission along with the folder name separated by space\n");
			scanf("%s %s", location1, location2);//entering the directory and new directory path
			strcat(location1, " ");strcat(location1, location2);
			path = location1;		
			printf("Path entered by you is %s\n", path);

			clnt = clnt_create (host, OPERATIONS, OPERATIONS_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

			result_4 = changemode_1(&path, clnt);

			if (result_4 == (char *) NULL) {
				printf("You dont have the Permission to edit the file\n");
				clnt_perror (clnt, "call failed");
			}

			printf("\nDirectory has been modified with the required operation\n---------------------------\n");

			clnt_destroy (clnt);


		}//chooses to change the mode of the directory or the file

	    else if(choice ==5){
			CLIENT *clnt; //declaring client
  			char *dir;
  			readdir_res *result_5;
  			namelist nl;
			char location[100];
			printf("Enter the Directory u want to list out\n");
			scanf("%s", location);//entering the directory and new directory path
			dir = location;		
			printf("Path entered by you is %s\n", dir);

			clnt = clnt_create (host, OPERATIONS, OPERATIONS_VERS, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

			result_5 = readdir_1(&dir, (struct CLIENT *)clnt);

			if (result_5 == (readdir_res *)NULL) {
				clnt_perror (clnt, "call failed");
			}


		
			if(result_5->err != 0){
			    err = result_5->err;
			    perror(dir);
			    exit(1);
			}
			printf("---------------------------\nListing Directory Contents\n");
			for (nl = result_5->readdir_res_u.list; nl != NULL; nl = nl->next){
			         printf("%s\n", nl->name);
			}

			printf("---------------------------\n");
			xdr_free((xdrproc_t)xdr_readdir_res,(char *) result_5);
			clnt_destroy (clnt);


		}
	}

 	clnt_destroy (clnt);
	exit (0);

}
}



